#模板： 表单 = [表单名，搜索后表单定位，数据表]
测试表单 = ["转正",'//*[@id="app"]/div/div[1]/div/div[2]/div/div[2]/div[2]/div[11]/div/p',r"D:\xiong\hello_world\auto_table\table_data\测试表单"]
网络平台 = ["网络平台",'//*[@id="app"]/div/div[1]/div/div[2]/div/div[2]/div[2]/div[6]/div/p',r"D:\xiong\hello_world\auto_table\table_data\网络平台"]
调配申请 = ["调配申请",'//*[@id="app"]/div/div[1]/div/div[2]/div/div[2]/div[2]/div[1]/div/p',r"D:\xiong\hello_world\auto_table\table_data\调配申请"]
辅岗申请 = ["辅岗申请",'//*[@id="app"]/div/div[1]/div/div[2]/div/div[2]/div[2]/div[7]/div/p',r"D:\xiong\hello_world\auto_table\table_data\辅岗申请"]
发放申请 = ["发放申请",'//*[@id="app"]/div/div[1]/div/div[2]/div/div[2]/div[2]/div[10]/div/p',r"D:\xiong\hello_world\auto_table\table_data\发放申请"]
离职提出申请 = ["离职提出申请",'//*[@id="app"]/div/div[1]/div/div[2]/div/div[2]/div[2]/div[3]/div/p',r"D:\xiong\hello_world\auto_table\table_data\离职提出申请"]
离职交接申请 = ["离职交接申请",'//*[@id="app"]/div/div[1]/div/div[2]/div/div[2]/div[2]/div[2]/div/p',r"D:\xiong\hello_world\auto_table\table_data\离职交接申请"]
录用申请 = ["录用申请",'//span[text()="录用申请"]',r"D:\xiong\hello_world\auto_table\table_data\录用申请"]
社保代缴 = ["社保代缴",'//span[text()="社保代缴"]',r"D:\xiong\hello_world\auto_table\table_data\社保代缴"]
培训管理金 = ["培训管理金",'//span[text()="培训管理金业务申请"]',r"D:\xiong\hello_world\auto_table\table_data\培训管理金"]
转正申请 = ["转正申请",'//span[text()="转正申请"]',r"D:\xiong\hello_world\auto_table\table_data\转正申请"]
编制调整 = ["编制调整",'//span[text()="编制调整"]',r"D:\xiong\hello_world\auto_table\table_data\编制调整"]
商品用车维修审核管理 = ["商品用车维修审核管理",'//span[text()="商品用车维修审核管理"]',r"D:\xiong\hello_world\auto_table\table_data\商品用车维修审核管理"]
考勤申请 = ["考勤事务审批",'//span[text()="考勤事务审批"]',r"D:\xiong\hello_world\auto_table\table_data\考勤申请"]
考勤修改申请 = ["考勤修改申请",'//span[text()="考勤修改申请"]',r"D:\xiong\hello_world\auto_table\table_data\考勤修改申请"]