# Generated by Django 3.0.7 on 2020-12-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_user',
            name='user',
            field=models.CharField(max_length=16, unique=True, verbose_name='账号'),
        ),
    ]
