# Generated by Django 3.0.7 on 2020-12-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20201221_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_user',
            name='passwd',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
    ]
