# Generated by Django 3.0.7 on 2020-12-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20201222_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_user',
            name='valid',
            field=models.IntegerField(default=1, verbose_name='生效'),
        ),
    ]
