# Generated by Django 3.2.7 on 2021-10-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20201222_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=32)),
                ('img', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=32)),
                ('m_class', models.IntegerField(default=1)),
            ],
        ),
    ]
