# Generated by Django 3.2.7 on 2021-10-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_movies_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='m_class',
        ),
    ]
